<a href="https://colab.research.google.com/github/roxoho/tennsorflow_learning/blob/main/introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [2]:
import numpy
import tensorflow as tf

In [5]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(321, tf.int16)
floating = tf.Variable(3.456, tf.float64)

In [6]:
rank1 = tf.Variable(['1',"0","True"],tf.string)
rank2 = tf.Variable([['1',"0","True"],['1',"0","True"]],tf.string)

In [7]:
print(tf.rank(string))
print(tf.rank(rank1))
print(tf.rank(rank2))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [13]:
rank3 = tf.Variable([[["d","d"],["d","d"],["d","d"],["d","d"]],[["d","d"],["d","d"],["d","d"],["d","d"]]],tf.string)
rank3.shape

TensorShape([2, 4, 2])

Changing Shapes

In [16]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [20]:
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor2,[3,-1])
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [25]:
tensors1 = tf.constant([1, 2, 3])
tensors2 = tf.constant([4, 5, 6])

# Perform operations
result = tf.add(tensors1, tensors2)

# Print or use the result directly
print(result.numpy())

[5 7 9]
